use super::Rarity;
use crate::stats::StatKind;
use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ItemKind {
    SpaceBorgar,
    MoonCheese,
    DuctTape,
    SlipperyVisor,
    ProteinPaste,
    OverclockedCpu,
    FishBowlHelmet,
    RocketBoots,
    TrampolineSoles,
    MagnetBoots,
    LuckyMeteorite,
    SpaceCreditCard,
    GoldenAntenna,
    StarChart,
    LaserSight,
    HeavyPayload,
    ExtraBattery,
    SplitterChip,
    CursedMoonRock,
    ThornPlating,
    VampireVisor,
    CaffeineIv,
}

pub struct ItemDef {
    pub kind: ItemKind,
    pub name: &'static str,
    pub desc: &'static str,
    pub rarity: Rarity,
    pub boosts: &'static [(StatKind, f32)],
    pub max_stacks: u32,
}

impl ItemKind {
    pub const ALL: [ItemKind; 22] = [
        ItemKind::SpaceBorgar,
        ItemKind::MoonCheese,
        ItemKind::DuctTape,
        ItemKind::SlipperyVisor,
        ItemKind::ProteinPaste,
        ItemKind::OverclockedCpu,
        ItemKind::FishBowlHelmet,
        ItemKind::RocketBoots,
        ItemKind::TrampolineSoles,
        ItemKind::MagnetBoots,
        ItemKind::LuckyMeteorite,
        ItemKind::SpaceCreditCard,
        ItemKind::GoldenAntenna,
        ItemKind::StarChart,
        ItemKind::LaserSight,
        ItemKind::HeavyPayload,
        ItemKind::ExtraBattery,
        ItemKind::SplitterChip,
        ItemKind::CursedMoonRock,
        ItemKind::ThornPlating,
        ItemKind::VampireVisor,
        ItemKind::CaffeineIv,
    ];

    pub fn def(&self) -> ItemDef {
        use ItemKind::*;
        use Rarity::*;
        use StatKind as S;
        match self {
            SpaceBorgar => ItemDef {
                kind: *self,
                name: "Space Borgar",
                desc: "Zero-g grease. Sticks to your ribs",
                rarity: Common,
                boosts: &[(S::MaxHp, 20.0)],
                max_stacks: 9,
            },
            MoonCheese => ItemDef {
                kind: *self,
                name: "Moon Cheese",
                desc: "Aged 4.5 billion years",
                rarity: Common,
                boosts: &[(S::Regen, 12.0)],
                max_stacks: 9,
            },
            DuctTape => ItemDef {
                kind: *self,
                name: "Duct Tape",
                desc: "Suit patch, armor plating, life philosophy",
                rarity: Common,
                boosts: &[(S::Armor, 8.0)],
                max_stacks: 9,
            },
            SlipperyVisor => ItemDef {
                kind: *self,
                name: "Slippery Visor",
                desc: "They literally cannot hit you",
                rarity: Rare,
                boosts: &[(S::Evasion, 8.0)],
                max_stacks: 6,
            },
            ProteinPaste => ItemDef {
                kind: *self,
                name: "Protein Paste",
                desc: "Tube gains",
                rarity: Common,
                boosts: &[(S::Damage, 0.10)],
                max_stacks: 9,
            },
            OverclockedCpu => ItemDef {
                kind: *self,
                name: "Overclocked CPU",
                desc: "Suit firmware set to UNSAFE",
                rarity: Rare,
                boosts: &[(S::AttackSpeed, 0.12)],
                max_stacks: 6,
            },
            FishBowlHelmet => ItemDef {
                kind: *self,
                name: "Fish Bowl Helmet",
                desc: "Bigger bubble, bigger booms",
                rarity: Rare,
                boosts: &[(S::Size, 0.12)],
                max_stacks: 6,
            },
            RocketBoots => ItemDef {
                kind: *self,
                name: "Rocket Boots",
                desc: "Walking is for Earth",
                rarity: Common,
                boosts: &[(S::MoveSpeed, 0.08)],
                max_stacks: 6,
            },
            TrampolineSoles => ItemDef {
                kind: *self,
                name: "Trampoline Soles",
                desc: "Boing certified",
                rarity: Common,
                boosts: &[(S::JumpHeight, 0.15)],
                max_stacks: 4,
            },
            MagnetBoots => ItemDef {
                kind: *self,
                name: "Magnet Boots",
                desc: "Loot learns to love you",
                rarity: Common,
                boosts: &[(S::PickupRange, 0.25)],
                max_stacks: 6,
            },
            LuckyMeteorite => ItemDef {
                kind: *self,
                name: "Lucky Meteorite",
                desc: "Statistically improbable rock",
                rarity: Epic,
                boosts: &[(S::Luck, 0.12)],
                max_stacks: 6,
            },
            SpaceCreditCard => ItemDef {
                kind: *self,
                name: "Space Credit Card",
                desc: "Interplanetary cashback",
                rarity: Rare,
                boosts: &[(S::ChestDiscount, 0.10)],
                max_stacks: 4,
            },
            GoldenAntenna => ItemDef {
                kind: *self,
                name: "Golden Antenna",
                desc: "Tuned to the money frequency",
                rarity: Rare,
                boosts: &[(S::GoldGain, 0.15)],
                max_stacks: 6,
            },
            StarChart => ItemDef {
                kind: *self,
                name: "Star Chart",
                desc: "Knowledge is XP",
                rarity: Rare,
                boosts: &[(S::XpGain, 0.10)],
                max_stacks: 6,
            },
            LaserSight => ItemDef {
                kind: *self,
                name: "Laser Sight",
                desc: "Red dot of destiny",
                rarity: Rare,
                boosts: &[(S::CritChance, 0.07)],
                max_stacks: 6,
            },
            HeavyPayload => ItemDef {
                kind: *self,
                name: "Heavy Payload",
                desc: "Crits with extra gravity",
                rarity: Epic,
                boosts: &[(S::CritDamage, 0.5)],
                max_stacks: 5,
            },
            ExtraBattery => ItemDef {
                kind: *self,
                name: "Extra Battery",
                desc: "Everything lasts longer",
                rarity: Rare,
                boosts: &[(S::Duration, 0.15)],
                max_stacks: 5,
            },
            SplitterChip => ItemDef {
                kind: *self,
                name: "Splitter Chip",
                desc: "One shot becomes friends",
                rarity: Legendary,
                boosts: &[(S::Projectiles, 1.0)],
                max_stacks: 2,
            },
            CursedMoonRock => ItemDef {
                kind: *self,
                name: "Cursed Moon Rock",
                desc: "Do NOT lick. More danger, more loot",
                rarity: Epic,
                boosts: &[(S::Difficulty, 0.15), (S::Luck, 0.10)],
                max_stacks: 5,
            },
            ThornPlating => ItemDef {
                kind: *self,
                name: "Thorn Plating",
                desc: "Hug at your own risk",
                rarity: Rare,
                boosts: &[(S::Thorns, 12.0)],
                max_stacks: 6,
            },
            VampireVisor => ItemDef {
                kind: *self,
                name: "Vampire Visor",
                desc: "Sunproof. Ironically",
                rarity: Epic,
                boosts: &[(S::Lifesteal, 0.05)],
                max_stacks: 4,
            },
            CaffeineIv => ItemDef {
                kind: *self,
                name: "Caffeine IV",
                desc: "Projectiles share your jitters",
                rarity: Common,
                boosts: &[(S::ProjSpeed, 0.15)],
                max_stacks: 6,
            },
        }
    }
}
